=== Graergis/home_4/test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/test/" targetNamespace="http://www.example.org/test/">
    
    <complexType name="Good">
    	<attribute name="Producer" type="string" use="required"></attribute>
    	<attribute name="Model" type="tns:ModelType" use="required"></attribute>
    	<attribute name="CreateDate" type="tns:DataType" use="required"></attribute>
    	<attribute name="Color" type="string" use="required"></attribute>
    	<attribute name="Cost" type="string" use="required"></attribute>
    	<attribute name="Quantity" type="string" use="required"></attribute>
    </complexType>
    
    <complexType name="SubCategory">
    	<sequence>
    		<element name="good" type="tns:Good" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>
    
    <complexType name="Categories">
    	<sequence>
    		<element name="category" type="tns:Category" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>    

    <complexType name="Category">
    	<sequence>
    		<element name="subCategory" type="tns:SubCategory" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <element name="categories" type="tns:Categories">
    </element>

    <simpleType name="ModelType">
    	<restriction base="string">
    		<pattern value="\d{3}[A-Z]{2}"></pattern>
    	</restriction>
    </simpleType>
    
    <simpleType name="DataType">
    	<restriction base="string">    	
    		<pattern value="\d{2}-\d{2}-\d{4}"></pattern>
    	</restriction>
    </simpleType>
</schema>

=== Graergis/home_4/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:categories xmlns:tns="http://www.example.org/test/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/test/ test.xsd ">
  <category name="Техника">
    <subCategory name="телевизор">
      <good Color="серый" Cost="17900" CreateDate="10-02-2016" Model="203PO" Producer="Samsung" Quantity="6"/>
    </subCategory>
    <subCategory name="магнитофон">
      <good Color="черный" Cost="2340" CreateDate="12-03-2016" Model="942RJ" Producer="неSamsung" Quantity="отсутствует"/>
    </subCategory>
    <subCategory name="пылесос">
      <good Color="синий" Cost="5670" CreateDate="07-01-2016" Model="283KF" Producer="Philips" Quantity="5"/>
    </subCategory>
    <subCategory name="холодильник">
      <good Color="белый" Cost="19900" CreateDate="11-04-2016" Model="341HR" Producer="отечественный" Quantity="3"/>
    </subCategory>
  </category>
</tns:categories>
